### ISSUE TITLE
visualstudio2022-workload-datascience is missing

### ISSUE THREAD

**Issue by ivanrusso** [jberezanski/ChocolateyPackages#123]
Package for the workload Microsoft.VisualStudio.Workload.DataScience is missing.

![image](https://user-images.githubusercontent.com/2790090/142643051-afc7edb1-9917-4104-a97d-381578a8d2da.png)

**Comment by jberezanski** [comment]
That's curious. I deliberately skipped this workload because the [workload/component list page](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022) did not mention it and it was not present in VS Installer in 17.0.0, so I thought it was removed in VS 2022.

**Comment by jberezanski** [comment]
Perhaps they added it back in 17.0.1..?

**Comment by jberezanski** [comment]
Reported the VS docs issue: https://github.com/MicrosoftDocs/visualstudio-docs/issues/7325

**Comment by jberezanski** [comment]
The package https://community.chocolatey.org/packages/visualstudio2022-workload-datascience is now published, pending moderator approval.

**Comment by jberezanski** [comment]
...and it's approved now.

**Comment by ivanrusso** [comment]
> ...and it's approved now.

Many thanks
