### ISSUE TITLE
KB3035131 throws an error if update is installed before the chocolatey package

### ISSUE THREAD

**Issue by benh57** [jberezanski/ChocolateyPackages#14]
Attmepting to install the KB3035131 pacakge on a Windows 7 system which already has it, throws the error. This should be considered a success case and not a failure.

Installing KB3035131...
WARNING: Update KB3035131 installation failed with code 0x00240006 (WU_S_ALREADY
_INSTALLED: The update to be installed is already installed on the system).
WARNING: More details may be found in the installation log (C:\Users\<>\AppD
ata\Local\Temp\chocolatey\KB3035131.Install.evt) or the system CBS log (C:\windo
ws\Logs\CBS\CBS.log).
ERROR: Update KB3035131 installation failed with code 0x00240006 (WU_S_ALREADY_I
NSTALLED: The update to be installed is already installed on the system).
The install of kb3035131 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\KB3035131\Tools\ChocolateyIns
tall.ps1'.

**Comment by jberezanski** [comment]
Whoa. I thought I already fixed this (#5). Could you please post your chocolatey.log?

**Comment by benh57** [comment]
Ah, it's theoretically possible i'm out of date, i'll check that Monday.

**Comment by jberezanski** [comment]
Perhaps the following scenario took place:
1) some time between 2017-02-05 and 2017-03-16 you installed a KB package (directly or as a dependency of something), which pulled chocolatey-windowsupdate.extension 1.0.1 as a dependency
2) on 2017-03-16 I published chocolatey-windowsupdate.extension 1.0.2 containing the WU_S_ALREADY_I
NSTALLED fix
3) you now install KB3035131 which depends on chocolatey-windowsupdate.extension 1.0.1 (because that version was the most current at the time of KB3035131 release); you have that extension version already installed, so choco sees no reason to upgrade it to 1.0.2; installation fails with WU_S_ALREADY_I
NSTALLED

Does this seem plausible?

The solution would be to re-publish KB3035131 (and possibly other KB packages) with the dependency version updated.

**Comment by benh57** [comment]
Yep, it does look like the chocolatey-windowsupdate-extension package i have is at 1.0.1, the KB package does not try to update it to 1.0.2.

After manually updating it to 1.0.2, kb3035131 installed fine. So yeah probably just updating the dependency version to 1.0.2 would fix.

thanks!

**Comment by jberezanski** [comment]
I've published the updated KB packages.
