### ISSUE TITLE
visualstudio2022buildtools fails to create or update offline layout

### ISSUE THREAD

**Issue by benh57** [jberezanski/ChocolateyPackages#148]
Not sure when this started or if it's just me, but sometime since April since it worked then. Maybe a change on the MS side? I've tried on a few machines.   If you aren't able to reproduce, then i can upload my full logs. 

Run:
`choco install -y visualstudio2022buildtools --params "--layout C:\test-offline --lang en-US"
`
Result:
The layout creation goes a few minutes, but exits before doing much. It does download the certificates. The only files in C:\test-offline created are:
```
vs_installer.version.json
certificates\vs_installer_opc.RootCertificate
```

I AM still able to create an offline layout manually using vs_buildtools.exe:

vs_BuildTools.exe --layout C:\test-offline

**Comment by ThomasPatzig** [comment]
confirm

I run:
```
choco install visualstudio2022buildtools --force --params "--layout C:\temp\test --add Microsoft.Component.MSBuild --lang en-us --quiet --wait --norestart"
```

it fails with
```
ERROR: The installation of visualstudio2022buildtools failed (installer exit code: 87).
The install of visualstudio2022buildtools was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2022buildtools\tools\ChocolateyInstall.ps1'.
 See log for details.
```

**Comment by ThomasPatzig** [comment]
for me it looks like that the --params "*" are not correctly transfered to the call of vs_BuildTools.exe after download

**Comment by ThomasPatzig** [comment]
same for "visualstudio2022enterprise"

**Comment by ThomasPatzig** [comment]
I used it now this workaround:

I call `choco install visualstudio2022buildtools --noop` and curl the latest vs_BuildTools.exe from `-Url`

then I call installer with parameters directly:
`
vs_BuildTools.exe --layout C:\temp\test --add Microsoft.Component.MSBuild --lang en-us --quiet --wait --norestart
`

but I hope the expected call via choco will be work again in future:
`choco install visualstudio2022buildtools --force --yes --params "--layout C:\temp\test --add Microsoft.Component.MSBuild --lang en-us --quiet --wait --norestart"`

**Comment by jberezanski** [comment]
Investigating.

**Comment by benh57** [comment]
Great news, thanks for fixing it! (while you're around maybe you could bump the packages to 17.7.4 :D

**Comment by jberezanski** [comment]
Yes, It was a bug in the package scripts - a recently added feature broke the layout creation due to unexpected behavior of the VS Installer in layout mode. I will publish a new version of `chocolatey-visualstudio.extension` soon.

I will not be publishing new versions of VS packages just to bump their dependencies, but the package dependencies will soon get updated when Microsoft releases new VS versions. Until then, in order to create a layout on a machine with VS already installed via choco, `chocolatey-visualstudio.extension` will need to be updated explicitly (`choco upgrade chocolatey-visualstudio.extension`).

@ThomasPatzig please note you do not need to pass `--quiet --wait --norestart` when using the VS choco packages, this is taken care for automatically.

**Comment by jberezanski** [comment]
Everything should be available on chocolatey.org now, including new versions of VS 2022 packages with dependency on the fixed extension. Could you please confirm the fix worked for you?

**Comment by ThomasPatzig** [comment]
ok, will check...

**Comment by jberezanski** [comment]
Great!
