### ISSUE TITLE
VS 2017 workloads fail to install due to registry Uninstall key changes in recent VS 2017 releases

### ISSUE THREAD

**Issue by maaktweluit** [jberezanski/ChocolateyPackages#28]
Running on windows server 2016
```
choco install visualstudio2017community
choco install visualstudio2017-workload-nativedesktop
```

Gives the error:
```
Exception calling "GetFullPath" with "1" argument(s): "The path is not of a legal form."
```

It seems the registry key for the installer has changed, when i change:
https://github.com/jberezanski/ChocolateyPackages/blob/814ab2a23b65afc30239452c7da634117d33258b/chocolatey-visualstudio.extension/extensions/Start-VisualStudioModifyOperation.ps1#L22
To look for "Installer" instead of $VisualStudioYear it works again.

**Comment by jberezanski** [comment]
Thanks, the uninstall registry keys indeed have changed.

(before:
"Microsoft Visual Studio 2017" under WOW6432Node\\...\Uninstall with UninstallString which uninstalls the entire VS Installer and all VS products managed by it
now (new in 15.5.0, I guess):
"Microsoft Visual Studio Installer" under the native (64-bit) Uninstall key with UninstallString which uninstalls the entire VS Installer and all VS products managed by it
"Microsoft Visual Studio $product 2017" under the native (64-bit) Uninstall key with UninstallString which uninstalls only this specific product)

I have already changed that function not to rely on the registry, as part of the upcoming `chocolatey-visualstudio.extension` 1.6.0 release. I will backport the change to 1.5.x, because there is still much testing to be done for 1.6.0.

Uninstallation of `visualstudio2017-installer` will also need changing - I think I will stop looking at the registry there, too.

**Comment by jberezanski** [comment]
Fixed in `chocolatey-visualstudio.extension` 1.5.1, published and already approved on chocolatey.org.

Also published `visualstudio2017-installer` and `visualstudio2017-workload-*` with updated dependency on that extension version - those packages are pending moderation.

**Comment by maaktweluit** [comment]
Thanks for looking into this and fixing it!

How long does the process on chocolatey take?
I'll close the issue when tested OK from the main repo.

**Comment by jberezanski** [comment]
The fixed extension is already public, so 1) new VS installations should pick it up automatically, 2) on existing VS installations you can take advantage of the fix right now by explicitly cup'ing chocolatey-visualstudio.extension before cinst'ing a workload.

I'm not sure how long the moderation queue is these days, but the changes in the workload packages are trivial (just a dependency version bump), so I expect them to be approved quickly once they reach the head of the queue.

**Comment by jberezanski** [comment]
This has been fixed for a few months now, so let's close the issue.
