### ISSUE TITLE
Add-VisualStudioWorkload fails w/o giving reason when VS Installer needs a self-update

### ISSUE THREAD

**Issue by userzimmermann** [jberezanski/ChocolateyPackages#52]
Hi @jberezanski :) First many thanks for your awesome Chocolatey packages!

Unfortunately, I experienced the following when trying to `choco install visualstudio2017-workload-vctools` (as also explained in https://chocolatey.org/packages/visualstudio2017-workload-vctools#comment-3982422101):

```
ERROR: Running ["C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools" --includeRecommended --norestart --quiet --add Microsoft.VisualStudio.Workload.VCTools] was not successful. Exit code was '1'. See log for possible error messages.
The install of visualstudio2017-workload-vctools was NOT successful.
```

Manually running ```"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools" --includeRecommended --norestart --add Microsoft.VisualStudio.Workload.VCTools``` w/o `--quiet` revealed that VS Installer wanted a self-update before performing anything else, although latest version of your `visualstudio2017-installer` package was installed

After manually performing that update process via the VS Installer GUI, `choco install visualstudio2017-workload-vctools` worked fine

Could your `chocolatey-visualstudio.extension` package somehow automatically handle such VS Installer updates? Does `vs_installer.exe` support that in some `--quiet` way? Or could `Start-VSModifyOperation` (or whatever cmdlet actually deals with `vs_installer.exe` figure our the actual problem and print a more helpful error message?

Kind regards,
Stefan

**Comment by jberezanski** [comment]
That's curious, because there is quite a lot of code in the extension devoted to the task of detecting the need to update the VS Installer and performing the update, and that code is [invoked](https://github.com/jberezanski/ChocolateyPackages/blob/master/chocolatey-visualstudio.extension/extensions/Start-VSModifyOperation.ps1#L281) before each modify operation.

Would you be able to provide your chocolatey.log (C:\ProgramData\Chocolatey\logs\chocolatey.log)? It should contain a lot of diagnostic info.

Also: the `visualstudio2017-installer` package does not install/update the installer - the purpose of this package is only to remove the installer after all VS products are uninstalled. It is much more important to have an up to date `chocolatey-visualstudio.extension` version, because the entire install logic is contained there (however, `visualstudio2017-workload-vctools` depends on the latest extension package version, so Chocolatey should automatically ensure the extension is up to date).

**Comment by jberezanski** [comment]
Closed due to lack of response.

**Comment by CriticalWill** [comment]
Can we reopen this? I have the same issue... Log attached.
[chocolatey.log](https://github.com/jberezanski/ChocolateyPackages/files/4995539/chocolatey.log)
