### ISSUE TITLE
upgrade dotnetfx to final 4.8?

### ISSUE THREAD

**Issue by rgl** [jberezanski/ChocolateyPackages#67]
Can you upgrade dotnetfx to final 4.8? :-)

**Comment by martincostello** [comment]
It is the final version, but it's just confusingly labelled (RTW = _Release to Web_) which makes it look like a prerelease in Chocolatey.

**Comment by rgl** [comment]
why not just drop "rtw" from the chocolatey version?

**Comment by jberezanski** [comment]
I was waiting for Microsoft to release it on Windows Update. It finally happened this month and I'm right now in the process of preparing packages without the prerelease suffix. (The installers were updated so a new round of testing was warranted.)

**Comment by jberezanski** [comment]
Update: I am now waiting for the [chocolatey-dotnetfx.extension](https://chocolatey.org/packages/chocolatey-dotnetfx.extension) package to be approved.

(Because there is quite a large number of .NET Framework / Developer Pack packages and that number will grow even further due to planned reorganization effort, I wanted to refactor the code to be able to maintain it effectively. I have already been burned recently by code duplication when I needed to make a fix for an issue with licensed Chocolatey.)

**Comment by jberezanski** [comment]
https://chocolatey.org/packages/dotnetfx/4.8.0.0

**Comment by rgl** [comment]
will we have a netfx-4.8-devpack?

**Comment by jberezanski** [comment]
I published the non-prerelease devpack yesterday shortly after the runtime. It's just awaiting moderator approval because it's not marked as trusted, unlike dotnetfx.
