### ISSUE TITLE
Access Denied When Deploying *.msu files

### ISSUE THREAD

**Issue by github4rocker** [jberezanski/ChocolateyPackages#69]
When trying to remotely update windows with chocolatey update extension the installation fails due to the following update:

https://blogs.technet.microsoft.com/sus/2012/10/30/kb-windows-update-standalone-installer-wusa-returns-0x5-error_access_denied-when-deploying-msu-files-through-winrm-and-windows-remote-shell/

Please integrate the following:

**Workaround**

To work around this issue, use the following method:

Extract the .msu file through Windows Remote Shell with WUSA using the following command:

winrs.exe -r:<computername> wusa.exe <update> /extract:<destination>

When complete, install the .cab package with dism.exe or Package Manager. To use dism.exe, use the command below:

winrs.exe -r:<computername> dism.exe /online /add-package /PackagePath:<Path_To_Package>\KBnnnnnnn.cab

**Comment by jberezanski** [comment]
I am relying on the `msu` file handling logic built into core Chocolatey, so this request should probably go to https://github.com/chocolatey/choco.

That said, it would be difficult to implement reliably, because the KB msu files:
- may contain not one, but several .cab files which should be applied in a certain order
- may contain rules (in an xml file) which tell wusa.exe the applicability rules of the KB (which OS, prerequisites etc) - we would need to implement logic to handle this
