### ISSUE TITLE
Upgrading visualstudio2019-workload-nativedesktop to v1.0.1 fails

### ISSUE THREAD

**Issue by Schroedingers-Cat** [jberezanski/ChocolateyPackages#98]
When upgrading [this previously successfully installed package](https://chocolatey.org/packages/visualstudio2019-workload-nativedesktop) for instance via:
```
choco upgrade visualstudio2019-workload-nativedesktop -ydv
```
It'll fail with 
```
ERROR: Die Zeichenfolge hat kein Abschlusszeichen: '.
```

which means basically that the string wasn't properly terminated. Here's the full verbose log: https://pastebin.com/pKrBX4xS

**Comment by jberezanski** [comment]
It seems to be crashing somewhere inside Chocolatey, before the package install script starts actually executing. You should probably report this to https://github.com/chocolatey/choco.

However, I can see from the log that you are using the choco feature "use remembered arguments for upgrades". This is not needed for Visual Studio packages and may, in fact, cause issues (#99). Here it seems that this is what triggers the bug inside choco (some quoting error).

As a last remark - the workload packages (`visualstudioNNNN-workload-*`) do not really need to be upgraded. Upon first installation, the package adds the workload to Visual Studio, but upgrading the package really has no effect. You need to upgrade the main, "product" package (in this case `visualstudio2019<community|enterprise|professional>`) in order to upgrade Visual Studio (regardless of what workloads were added).

**Comment by jberezanski** [comment]
Closing as it seems to be an issue with choco.exe, not with the package.
